spring.application.name=Thesis

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/thesisdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration