CREATE TABLE user_account
(
    github_id     BIGINT PRIMARY KEY,
    login         VARCHAR(255),
    display_name  VARCHAR(255),
    role          VARCHAR(30) NOT NULL,
    last_login_at TIMESTAMP
);

CREATE TABLE supervisor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255),
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    office     VARCHAR(255),
    phone      VARCHAR(255)
);

CREATE TABLE topic
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_id BIGINT,
    title         VARCHAR(255) NOT NULL,
    description   TEXT,
    CONSTRAINT fk_supervisor FOREIGN KEY (supervisor_id) REFERENCES supervisor (id) ON DELETE CASCADE
);

CREATE TABLE field_tag
(
    supervisor_id BIGINT      NOT NULL,
    field_name    VARCHAR(50) NOT NULL,
    PRIMARY KEY (supervisor_id, field_name),
    CONSTRAINT fk_field_supervisor FOREIGN KEY (supervisor_id) REFERENCES supervisor (id)
);

INSERT INTO SUPERVISOR (FIRST_NAME, LAST_NAME, EMAIL, TITLE)
VALUES ('Max', 'Mustermann', 'max@hhu.de', 'Dr.');

INSERT INTO TOPIC (SUPERVISOR_ID, TITLE, DESCRIPTION)
VALUES (1, 'Testtopic', 'Testtopic Beschreibung');

INSERT INTO FIELD_TAG (SUPERVISOR_ID, FIELD_NAME)
VALUES (1, 'Java');