CREATE TABLE user_account
(
    github_id     BIGINT PRIMARY KEY,
    login         VARCHAR(255),
    display_name  VARCHAR(255),
    role          VARCHAR(30) NOT NULL,
    last_login_at TIMESTAMP
);

CREATE TABLE supervisor
(
    supervisor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT                     NOT NULL,
    public_id     UUID DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    title         VARCHAR(255),
    first_name    VARCHAR(255)               NOT NULL,
    last_name     VARCHAR(255)               NOT NULL,
    email         VARCHAR(255)               NOT NULL,
    office        VARCHAR(255),
    phone         VARCHAR(255)
);

CREATE TABLE topic
(
    topic_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_id BIGINT,
    title         VARCHAR(255) NOT NULL,
    description   TEXT,
    CONSTRAINT fk_supervisor FOREIGN KEY (supervisor_id) REFERENCES supervisor (supervisor_id) ON DELETE CASCADE
);

CREATE TABLE field_tag
(
    supervisor_id BIGINT       NOT NULL,
    field_name    VARCHAR(255) NOT NULL,
    PRIMARY KEY (supervisor_id, field_name),
    CONSTRAINT fk_field_supervisor FOREIGN KEY (supervisor_id) REFERENCES supervisor (supervisor_id) ON DELETE CASCADE
);

CREATE TABLE student
(
    student_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT       NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL
);

CREATE TABLE course
(
    student_id BIGINT       NOT NULL,
    course     VARCHAR(255) NOT NULL,
    PRIMARY KEY (student_id, course),
    CONSTRAINT fk_course_student FOREIGN KEY (student_id) REFERENCES student (student_id) ON DELETE CASCADE
);

CREATE TABLE interest
(
    student_id BIGINT       NOT NULL,
    interest   VARCHAR(255) NOT NULL,
    PRIMARY KEY (student_id, interest),
    CONSTRAINT fk_interest_student FOREIGN KEY (student_id) REFERENCES student (student_id) ON DELETE CASCADE
);